# Generated by Django 3.1 on 2020-08-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200814_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/base_image.png', null=True, upload_to='images/'),
        ),
    ]
